import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Biology Web of Connections",
  description: "Developed by Joshua Haupt and Daniel Mace.\nGenerated by create next app.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
